kind: PersistentVolume
apiVersion: v1
metadata:
  name: new-init-volume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /testdata
  claimRef:
    namespace: default
    name: new-init-volume
