apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: leaderset
  labels:
    name: leaderset
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      name: leaderset
  template:
    metadata:
      labels:
        name: leaderset
    spec:
      serviceAccountName: leader-elector
      containers:
      - name: elector
        image: gcr.io/google_containers/leader-elector:0.5
        imagePullPolicy: IfNotPresent
        args:
          - --election=monolith-jobs
          - --http=localhost:4040
        ports:
          - containerPort: 4040
            protocol: TCP